export const CREATE_VOICE_ROOM = 'CREATE_VOICE_ROOM ';
export const CLOSE_POPUP = 'CLOSE_POPUP';

export const NEW_MESSAGE_RECEIVED = 'NEW_MESSAGE_RECEIVED'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const CHANGE_CURRENT_MESSAGE = 'CHANGE_CURRENT_MESSAGE'
export const ENTER_NAME = 'ENTER_NAME'
export const CHANGE_NAME = 'CHANGE_NAME'
export const CHANGE_KEY = 'CHANGE_KEY'
export const USERS_LOADED = 'USERS_LOADED'
export const NEW_USER = 'NEW_USER'
export const CHANGE_VOLUME = 'CHANGE_VOLUME'
export const TOGGLE_MUTE_USER = 'TOGGLE_MUTE_USER'
export const USER_DISCONNECTED = 'USER_DISCONNECTED'
export const START_MICROPHONE = 'START_MICROPHONE'
export const STOP_MICROPHONE = 'STOP_MICROPHON'
export const START_SOUND = 'START_SOUND'
export const STOP_SOUND = 'STOP_SOUND'
export const CHANGE_INPUT_VOLUME = 'CHANGE_INPUT_VOLUME'
export const CHANGE_OUTPUT_VOLUME = 'CHANGE_OUTPUT_VOLUME'
export const CHANGE_VOLUME_GATE = 'CHANGE_VOLUME_GATE'



export const START_CONNECTION = 'START_CONNECTION'
export const CLOSE_CONNECTION = 'CLOSE_CONNECTION'
export const JOIN = 'JOIN'
export const GET_OTHER_USERS = 'GET_OTHER_USERS'
export const START_LISTENING = 'START_LISTENING'
export const SEND_VOICE = 'SEND_VOICE'
export const USER_VOICE_ENDED = 'USER_VOICE_ENDED'

export const USER_SPEAKING = 'USER_SPEAKING'
export const VOICE_ENDED = 'VOICE_ENDED'